spring:
  redis:
    host: 106.53.53.176
    port: 6379
    database: 0
    timeout: 10000 #连接超时时间(毫秒)
    lettuce:
      pool:
        max-active: 8  #连接池最大连接数(为负数没有限制)
        max-wait: 10000  #最大阻塞时间(为负数没有限制)
        max-idle: 8  #最大空闲连接数
        min-idle:  0  # 最小空闲连接数
      shutdown-timeout: 100 #关闭超时时间